In [71]:
from sklearn.model_selection import train_test_split, KFold
import numpy as np
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [72]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [73]:
y1 = np.where(y==1)[0]
y0 = np.where(y==0)[0] 

In [74]:
y1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39], dtype=int64)

In [75]:
x_train_y1, x_test_y1, y_train_y1, y_test_y1 = train_test_split(X[y1], y[y1], test_size=10)
x_train_y0, x_test_y0, y_train_y0, y_test_y0 = train_test_split(X[y0], y[y0], test_size=10)

In [76]:
x_train_y1

array([[190, 191, 192, 193, 194],
       [105, 106, 107, 108, 109],
       [ 90,  91,  92,  93,  94],
       [165, 166, 167, 168, 169],
       [145, 146, 147, 148, 149],
       [ 15,  16,  17,  18,  19],
       [100, 101, 102, 103, 104],
       [185, 186, 187, 188, 189],
       [ 75,  76,  77,  78,  79],
       [ 55,  56,  57,  58,  59],
       [180, 181, 182, 183, 184],
       [150, 151, 152, 153, 154],
       [ 85,  86,  87,  88,  89],
       [160, 161, 162, 163, 164],
       [155, 156, 157, 158, 159],
       [  0,   1,   2,   3,   4],
       [195, 196, 197, 198, 199],
       [ 25,  26,  27,  28,  29],
       [175, 176, 177, 178, 179],
       [140, 141, 142, 143, 144],
       [135, 136, 137, 138, 139],
       [ 20,  21,  22,  23,  24],
       [ 60,  61,  62,  63,  64],
       [ 45,  46,  47,  48,  49],
       [ 80,  81,  82,  83,  84],
       [ 70,  71,  72,  73,  74],
       [110, 111, 112, 113, 114],
       [  5,   6,   7,   8,   9],
       [ 50,  51,  52,  53,  54],
       [ 95,  

In [80]:
x_train_y0

array([[665, 666, 667, 668, 669],
       [730, 731, 732, 733, 734],
       [725, 726, 727, 728, 729],
       [245, 246, 247, 248, 249],
       [240, 241, 242, 243, 244],
       [340, 341, 342, 343, 344],
       [590, 591, 592, 593, 594],
       [755, 756, 757, 758, 759],
       [540, 541, 542, 543, 544],
       [615, 616, 617, 618, 619],
       [200, 201, 202, 203, 204],
       [700, 701, 702, 703, 704],
       [900, 901, 902, 903, 904],
       [795, 796, 797, 798, 799],
       [355, 356, 357, 358, 359],
       [570, 571, 572, 573, 574],
       [985, 986, 987, 988, 989],
       [250, 251, 252, 253, 254],
       [305, 306, 307, 308, 309],
       [685, 686, 687, 688, 689],
       [470, 471, 472, 473, 474],
       [350, 351, 352, 353, 354],
       [960, 961, 962, 963, 964],
       [405, 406, 407, 408, 409],
       [910, 911, 912, 913, 914],
       [935, 936, 937, 938, 939],
       [660, 661, 662, 663, 664],
       [535, 536, 537, 538, 539],
       [740, 741, 742, 743, 744],
       [330, 3

In [77]:
x_train, y_train = np.concatenate([x_train_y1, x_train_y0]), np.concatenate([y_train_y1, y_train_y0])

In [78]:
x_test, y_test = np.concatenate([x_test_y1, x_test_y0]), np.concatenate([y_test_y1, y_test_y0])

In [79]:
y_test

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])